name: Next Build
on:
  pull_request:
    branches-ignore:
      - main
      - development
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: setup-node
        uses: actions/setup-node@v3
        with:
          node-version: [16.x]
          cache: "yarn"

      - name: yarn-install
        run: yarn install
      - name: app-build
        run: yarn build
      - name: yarn lint
        run: yarn lint
      - name: yarn tsx
        run: yarn tsc
      - name: yarn storybook
        run: yarn build-storybook
