name: lint-check

on:
  push:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [17.x]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.cache/yarn
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Install dependencies
        run: yarn install
      - name: Run lint check
        run: yarn lint
      - name: Run tsc
        run: yarn tsc
      - name: Run test
        run: yarn test:coverage && cat ./coverage/lcov.info | ./node_modules/.bin/coveralls
      - name: Istanbul coverage check
        run: |
          if [ $(echo "$(cat ./coverage/lcov.info | ./node_modules/.bin/coveralls | cut -d ' ' -f 2) < 80" | bc -l) -eq 1 ]; then
            echo "Coverage is below 80% threshold."
            exit 1
          fi
      - name: Reviewdog
        uses: reviewdog/action-eslint@v1
        with:
          eslint-github-check-bright: true
